auths:
  public_v2:
    community: public
    version: 2

# NEW: All modules must be nested under this 'modules' key
modules:
  rpi_module:
    walk:
    - 1.3.6.1.3.99
    metrics:
    - name: rpiCpuTemp
      oid: 1.3.6.1.3.99.1.1
      type: gauge
      help: The current CPU temperature of the Raspberry Pi in Celsius.
      regex_extracts:
        '':
        - regex: '([0-9\.]+)'
          value: '$1'
    - name: rpiCpuLoad
      oid: 1.3.6.1.3.99.1.2
      type: gauge
      help: The current CPU load as a percentage (0-100).